### ISSUE TITLE
Nbxplorer hard coded volumes claim 

### ISSUE THREAD

**Issue by Ashleyhen** [duck1123/chart.kronkltd.net#1]
The claimName is currently a hardcode value, ideally the this should be more dynamic to accommodate pods with custom names 

```yml
volumes:
        - name: nbxplorer
          persistentVolumeClaim:
            claimName: nbxplorer
```
Ideally something like this 
```yml
  volumes:
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "fileserver.fullname" .) }}
        {{- else }}
```
