### ISSUE TITLE
Allow for dynamic arguments 

### ISSUE THREAD

**Issue by Ashleyhen** [duck1123/chart.kronkltd.net#2]
The arguments should be configurable in the values.yaml file, consider utilizing the settings.config file.
```yaml
   containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          # command: [ "/bin/bash", "-c", "sleep 3600" ]
          args:
            - "--datadir=/data"
            - "--bind=0.0.0.0:32838"
            - "--network={{ .Values.nbxplorer.network }}"
            - "--chains={{ .Values.nbxplorer.chain }}"
            - "--regtest"
            - "--noauth"
            - "--btcrpcurl={{ .Values.nbxplorer.rpcurl }}"
            - "--btcnodeendpoint={{ .Values.nbxplorer.nodeEndpoint}}"
            - "--btcrpcauth={{ .Values.config.rpcauth }}"
            - "--rmquser={{ .Values.rabbitmq.auth.username }}"
            - "--rmqpass={{ .Values.rabbitmq.auth.password }}"
            - "--rmqhost=nbxplorer-rabbitmq"
            - "--rmqvirtual=/"
            - "--rmqtranex=NewTransaction"
            - "--rmqblockex=NetBlock"
```
